### ISSUE TITLE
Deprecations

### ISSUE THREAD

**Issue by dirkdirk** [mthadley/outlander-syntax#4]
Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

atom-text-editor, :host => atom-text-editor,atom-text-editor
...

**Comment by mthadley** [comment]
Thanks! I've also seen the deprecations, I just have not gotten around to it yet.
